getStepsAndResult now return a List<Map.Entry<String, String>> instea…
cucumber/cucumber-junit-xml-formatter pull request #24
Opened 2024-02-02 16:05 UTC by fahadi-henix

Linked to this bug : https://github.com/cucumber/cucumber-junit-xml-formatter/issues/23

### 🤔 What's changed?

The xml report formatter now returns the same number of step results as the number of steps in a cucumber test, even if some steps have the same name.
In code :
`XmlReportData.getStepsAndResult()` now returns a `List<Map.Entry<String, String>>` instead of a `LinkedHashMap<String, String>`
`XmlReportWriter.createStepResultList()` now take a `List<Map.Entry<String, String>>` instead of a `LinkedHashMap<String, String>` as parameter

### ⚡️ What's your motivation? 

motivation was to fix this bug : 
https://github.com/cucumber/cucumber-junit-xml-formatter/issues/23

### 🏷️ What kind of change is this?

- :bug: Bug fix (non-breaking change which fixes a defect)

### ♻️ Anything particular you want feedback on?

### 📋 Checklist:

- [x] I agree to respect and uphold the [Cucumber Community Code of Conduct](https://cucumber.io/conduct/)
- [x] I've changed the behaviour of the code
  - [ ] I have added/updated tests to cover my changes.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [x] Users should know about my change
  - [ ] I have added an entry to the "Unreleased" section of the [**CHANGELOG**](../blob/main/CHANGELOG.md), linking to this pull request.

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

2024-02-02 18:09 UTC, mpkorstanje requested changes
The implementation looks good!

But please clean up the issue name, and put that in the changelog a long with a reference to issue. 

Typically a good issue name, and good change log entry follow the guidelines of a good commit title.

https://cbea.ms/git-commit/

Please also look at the existing entries and ensure consistency.

2024-02-05 08:56 UTC, fahadi-henix commented
@mpkorstanje Thanks for the review ! I Think I did the requested changes

2024-02-08 19:52 UTC, mpkorstanje approved these changes
LGTM. Cheers!

I currently don't have Ethernet and USB tethering to my phone doesn't work. I'll release this asap.

2024-02-15 19:29 UTC, merged

2024-02-15 19:29 UTC, aslakhellesoy commented
Hi @fahadi-henix,

Thanks for your making your first contribution to Cucumber, and welcome to the Cucumber committers team! You can now push directly to this repo and all other repos under the cucumber organization! 🍾

In return for this generous offer we hope you will:

* ✅ Continue to use branches and pull requests. When someone on the core team approves a pull request (yours or someone else's), you're welcome to merge it yourself.
* 💚 Commit to setting a good example by following and upholding our [code of conduct](https://cucumber.io/conduct) in your interactions with other collaborators and users.
* 💬 Join the [community Slack channel](http://cucumber.io/support#slack) to meet the rest of the team and make yourself at home.
* ℹ️ Don't feel obliged to help, just do what you can if you have the time and the energy.
* 🙋 Ask if you need anything. We're looking for feedback about how to make the project more welcoming, so please tell us!

On behalf of the Cucumber core team,
Aslak Hellesøy
Creator of Cucumber